---
- name: Update apt-get repository and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Install list of packages
  apt:
    name: "{{ docker_packages }}"
    state: latest

- name: Add Docker’s official GPG key
  apt_key: url={{ docker_gpg_key_url }}

- name: Set up a stable Docker repository 
  apt_repository:
    repo: deb [arch={{ architecture }}] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

- name: Install Docker Engine
  apt:
    name: "{{ docker_engine }}"
    state: latest

- name: Run Java-app container
  shell: docker run --name {{ container_name }} -d -it {{ docker_image }} /bin/bash
